# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_codebook', '0002_auto_20210511_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapointtype',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapointtype',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
