# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_codebook', '0003_auto_20210511_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapointtype',
            name='generator',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
