# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passive_data_kit_codebook', '0004_auto_20210520_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapointtype',
            name='description',
            field=models.TextField(default='{}', max_length=67108864),
        ),
    ]
